### ISSUE TITLE
crypto.randomUUID() is not a function

### ISSUE THREAD

**Issue by fakemancat** [sudomakes/backroad#13]
Hello, I encountered an error when I transferred a project from my local machine to the server.

localhost works:
![chrome_ksqR4538jK](https://github.com/sudomakes/backroad/assets/33839807/7f7ae162-907f-48dd-a1c6-1b6fa919e4e6)

Doesn't work on the server:
![image](https://github.com/sudomakes/backroad/assets/33839807/3f0c6881-3bb0-41ca-ac42-f11ea1d1c49f)

**Comment by sudo-vaibhav** [comment]
I think you sorted it out on your own! Cheers 🍺

**Comment by sudo-vaibhav** [comment]
@fakemancat if you do end up hosting this project of yours, feel free to share a link with me. I'd love to see what people are building with backroad.

**Comment by fakemancat** [comment]
@sudo-vaibhav have u a telegram profile?

**Comment by sudo-vaibhav** [comment]
Yes, message me on telegram on @sudomakes
