### ISSUE TITLE
crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by 2213500360** [sudomakes/backroad#14]
Hi. The code functioned perfectly in the local environment now, but I encountered an issue when deploying it to an AWS EC2 instance. When attempting to access the application using the public IP and port, I received the following error message: "crypto.randomUUID is not a function". I attempted to resolve this by changing various Node.js versions, but to no avail. 
Ultimately, I was able to resolve the issue by eliminating the crypto.randomUUID function call from the file "backroad\src\lib\server\public\assets\index-ea1de61e.js", and now the application is functioning properly. 
However, I'm still uncertain about the root cause of this problem .
THX

**Comment by sudo-vaibhav** [comment]
This is the cause: https://github.com/sudomakes/backroad/issues/13
