### ISSUE TITLE
feature: add clipboard based file upload instead of having to pick from filesystem 

### ISSUE THREAD

**Issue by sudo-vaibhav** [sudomakes/backroad#15]

**Comment by Anand-Theertha** [comment]
Hello @sudo-vaibhav, could you please elaborate on this issue?

**Comment by sudo-vaibhav** [comment]
If you check out how file upload component works, you'd see that only files stored on disk are allowed to be picked on backroad. That's good but what we would like is also being able to let's say copy an image that's on your clipboard directly, since that's often more convenient, especially for things like screenshots which often don't need to be written to Filesystem, and consumed directly, maybe we can add an icon on the file upload component, and that copies from your clipboard

**Comment by sudo-vaibhav** [comment]
merged to alpha
