### ISSUE TITLE
feature: Default Colors for Doughnut & Pie Charts

### ISSUE THREAD

**Issue by alphaxek** [sudomakes/backroad#17]
Hi,

Considering the framework's goal of making the selection of colors hassle-free, we still need to pass the colors to doughnut and pie charts. If we don't pass them, the framework applies one color to all of them.

**Reference:**
![image](https://github.com/sudomakes/backroad/assets/116849110/f8de120a-3261-45e2-8d58-da3aa6cdd558)

I think we can have two options for this: either pass the colors of your choice, or let it pick a default set of hassle-free colors that align with the framework's goal.

**Comment by sudo-vaibhav** [comment]
I agree with you and if you look at the code, I had even used this package called "chartjs-plugin-autocolors" to sort of do what you want. But maybe it's something wrong with how I have invoked this plugin or the plugin itself that the chart coloring doesn't quite work

**Comment by alphaxek** [comment]
Hi, Yes I went through the code where you used 'chartjs-plugin-autocolors' and commented out the colors data in data.js. I believe it was never fully implemented, possibly due to its complexity.

**Comment by alphaxek** [comment]
Hi, I believe there are two ways to accomplish this..
 1. Write code to create custom BackroadComponents specifically for Pie and Doughnut charts, utilizing the `chartjs-plugin-autocolors` library instead of `chartjs` directly.
 2. Implement a workaround in `backroad.ts` to include default props if they are not explicitly passed..


Not sure if doing the 2nd way is the correct way but I have tested it from my end, and it functions as expected. There is room for improvement in the logic, such as handling cases where the user provides 4 data objects but only 2 colors. Currently, the implementation lacks modularity, as all the logic is within a single function. Users have the flexibility to provide both `backgroundColor` and `borderColor` or just either one of them.

**backroad.ts:**
![image](https://github.com/sudomakes/backroad/assets/116849110/521b7ba6-dfc2-4cb0-8ce0-5b6e8dff037d)

**doughnut_chart.ts:**
![image](https://github.com/sudomakes/backroad/assets/116849110/fd934bc3-5d8e-4053-b5fe-e0a2819866e3)

**Test:**
![image](https://github.com/sudomakes/backroad/assets/116849110/61c9f1c1-2988-4525-8a19-7bccd6ddbe05)

**Comment by sudo-vaibhav** [comment]
this change will only work for doughnut right, instead of being generally useful across all chart types?

**Comment by alphaxek** [comment]
yes true, let me see if I can generalize it
