### ISSUE TITLE
Request to Add Data Labels to Charts

### ISSUE THREAD

**Issue by TL-SWFT** [sudomakes/backroad#5]
I need to add data labels to the bar, but it seems that this functionality has not been implemented. I'm uncertain if this feature is already part of the library's capabilities. If it's not currently available, I kindly inquire whether it could be considered for implementation in future updates. Thank you for your attention to this matter.This is my [code](https://stackblitz.com/edit/stackblitz-starters-tfac9w).

- OS: Windows 11 22000.2538
- Package Version: 1.3.0
- node Version: 20.9.0

**Comment by sudo-vaibhav** [comment]
Could you explain what you mean by "data labels to the bar"?

**Comment by sudo-vaibhav** [comment]
<img width="286" alt="image" src="https://github.com/sudomakes/backroad/assets/53619134/4a813cdb-96c0-4d3f-b291-c73d3998eef2">

You can see labels on hover, and also at the bottom in this example, is there anything else you are looking for?

**Comment by sudo-vaibhav** [comment]
also just so you know the charting features of backroad are based on react chart js 2, so anything that sdk allows should be doable using backroad

**Comment by sudo-vaibhav** [comment]
We could consider adding this package.  We also need to consider the implication this would have on the bundle size. 

 We want users to be able to render "good-enough" looking charts that mostly get the job done on the app they are building rather than optimize and accommodate every possible thing.
