### ISSUE TITLE
Instructions unclear for dev setup

### ISSUE THREAD

**Issue by sudo-vaibhav** [sudomakes/backroad#6]
Currently if you clone this repo, and start the project, it's not very clear that frontend and backend are decoupled in dev. We should improve our log messages to better explain what's going on under the hood.

**Comment by sudo-vaibhav** [comment]
@jakusha let's continue our conversation so that your debugging process also serves as a guide for other developers to get started with backroad in the mean time we work on better documentation.

**Comment by sudo-vaibhav** [comment]
Regarding the docker file, you need not worry about it, that's just for building a toy backroad app which I used to deploy to https://br.sudomakes.art before I figured out how to automate publishing to npm for my own testing purposes

**Comment by jakusha** [comment]
> @jakusha let's continue our conversation so that your debugging process also serves as a guide for other developers to get started with backroad in the mean time we work on better documentation.

alright then, will complete the contribution guide

**Comment by sudo-vaibhav** [comment]
This has been resolved and is currently in alpha, new message looks something like:

<img width="526" alt="image" src="https://github.com/sudomakes/backroad/assets/53619134/073c96f6-3557-42fa-9e0d-7ad231add0c2">

**Comment by jakusha** [comment]
Hey, I will check out the alpha branch for the fix.

**Comment by sudo-vaibhav** [comment]
fixed and merged
