### ISSUE TITLE
Request to Add Support for More File Types to the fileUpload Component

### ISSUE THREAD

**Issue by TL-SWFT** [sudomakes/backroad#8]
The current fileUpload component only supports image uploads. If the component's functionality could be expanded to support a wider range of file types, such as xlsx, csv, etc., I would be very grateful.:)

**Comment by sudo-vaibhav** [comment]
I don't think that's the case, you should be able to specify your own file extensions of choice, just like how you do in html file inputs, if that doesn't work let me know and someone can work on fixing it.

**Comment by sudo-vaibhav** [comment]
Ah I see, there is an option to pass file extensions to the component but the actual extension is hard coded in the component

https://github.com/sudomakes/backroad/blob/7df10d5b32c728e97832a8e3ad8f023d4ab886bc/libs/backroad-client/src/lib/components/file_upload.tsx#L48C5-L48C5

**Comment by lambagayatri08** [comment]
Working on this

**Comment by sudo-vaibhav** [comment]
![image](https://github.com/sudomakes/backroad/assets/53619134/f4177377-c3ee-417c-bd30-ddf58a8d1185)

I have tested the fix and will be trying to release it on the beta channel soon. Now you can specify a format of your choice using the convention followed by react dropzone, more on that here : https://react-dropzone.org/#!/Accepting%20specific%20file%20types

**Comment by sudo-vaibhav** [comment]
This was my code:
```
    const [htmlFile] = br.fileUpload({
      accept: {
        'text/html': ['.html', '.htm'],
      },
      label: 'Pick an HTML File',
    });
    if (htmlFile) {
      br.write({ body: readFileSync(htmlFile.filepath).toString() });
    }
```

**Comment by sudo-vaibhav** [comment]
@TL-SWFT I have released version 1.3.1-alpha.1 Please check and verify if it meets your expectations.

**Comment by sudo-vaibhav** [comment]
That's expected since now file type is in accordance with react drop zone, which wants an object. I hope it's not too much of a problem to account for this in your code.

**Comment by sudo-vaibhav** [comment]
fixed and merged
