### ISSUE TITLE
Table Content Doesn't Update with Option Changes

### ISSUE THREAD

**Issue by TL-SWFT** [sudomakes/backroad#9]
When I have two radio buttons in my options, labeled as 1 and 2, but I select '2' in the options box, the table content does not change with the option selection. I would greatly appreciate it if these issues could be resolved, and if a default value could be provided for the options.:)

this is my [code](https://stackblitz.com/edit/stackblitz-starters-92fjwv?file=index.js)

**Comment by sudo-vaibhav** [comment]
I think the tanstack table package being used is being too aggressive here in not allowing view updates. Fixing this will require some some insight into how to appropriately force a re-render on that component. Let me think about how to best solve this. I personally don't have a good idea about how to fix this as of now. Others feel free to chime in if you have any idea on how to fix this

**Comment by sudo-vaibhav** [comment]
Ah yes, that's there. I did not think of that 😅. BTW thank you for pushing backroad to its limits and finding these bugs out, it's going to help this project out a lot. Also do share what you are building using backroad with me if possible, I'd love to check it out.

**Comment by sudo-vaibhav** [comment]
Fixed in 1.3.1-alpha.4, @TL-SWFT, once you can confirm if it's working for you, I will merge it into the mainline.

**Comment by sudo-vaibhav** [comment]
fixed in 1.3.1

**Comment by sudo-vaibhav** [comment]
On a side note, what other features or components would you like to be added? I am trying to get feedback regarding which features should be built next. A few that come to my mind are integration for analytics tools like Google Analytics, and authentication support for making backroad apps auth-walled if needed. Do you have any other suggestions or requirements which you feel can enhance the project @TL-SWFT?
